name: Build and Deploy RPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: fedora-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo dnf install -y python3-pip rpmdevtools rpmlint

      - name: Set up RPM development tree
        run: rpmdev-setuptree

      - name: Install Python dependencies
        run: pip3 install --no-cache-dir requests pyinstaller setuptools

      - name: Build the Python project with PyInstaller
        run: pyinstaller --onefile app.py --name=vcandy

      - name: Create binary folder
        run: mkdir vcandy-2.0

      - name: Move binary to binary folder
        run: mv dist/vcandy vcandy-2.0

      - name: Create .tar.gz file
        run: tar --create --file vcandy-2.0.tar.gz vcandy-2.0

      - name: Move .tar.gz to SOURCES directory
        run: mv vcandy-2.0.tar.gz ~/rpmbuild/SOURCES

      - name: Create spec file
        run: |
          cat <<EOF > ~/rpmbuild/SPECS/vcandy.spec
          Summary: A python CLI application that installs automatic container and virtualization tools for many Linux systems
          Name: vcandy
          Version: 2.0
          Release: 1%{?dist}
          License: MIT
          URL: https://github.com/Hakanbaban53/Container-and-Virtualization-Installer
          Source0: %{name}-%{version}.tar.gz

          %description
          vcandy is a command-line tool that simplifies the installation process of container and virtualization tools on Linux systems.

          %prep
          %setup -q

          %install
          rm -rf \$RPM_BUILD_ROOT
          mkdir -p \$RPM_BUILD_ROOT/%{_bindir}
          cp %{name} \$RPM_BUILD_ROOT/%{_bindir}

          %clean
          rm -rf \$RPM_BUILD_ROOT

          %files
          %{_bindir}/%{name}

          %changelog
          * Thu Mar 19 2024 Hakan İSMAİL <hakanismail53@gmail.com> - 2.0
          - Initial release
          EOF

      - name: Build RPM package
        run: rpmbuild -bb ~/rpmbuild/SPECS/vcandy.spec

      - name: Upload RPM package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vcandy
          path: ~/rpmbuild/RPMS/**/*.rpm
