name: Build and Deploy RPM

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt install -y python3-pip rpm


      - name: Install Python dependencies
        run: pip3 install --no-cache-dir requests pyinstaller setuptools

      - name: Build the Python project with PyInstaller
        run: pyinstaller --onefile /home/runner/work/Virtual-CANDY/Virtual-CANDY/app.py --name=vcandy

      - name: Create spec file
        run: |
          cat <<EOF > ~/vcandy.spec
          Summary: A python CLI application that installs automatic container and virtualization tools for many Linux systems
          Name: vcandy
          Version: 2.0
          Release: 1%{?dist}
          License: MIT
          URL: https://github.com/Hakanbaban53/Virtual-CANDY
          Source0: %{name}-%{version}.tar.gz
          
          %description
          vcandy is a command-line tool that simplifies the installation process of container and virtualization tools on Linux systems.
          
          %prep
          %setup -q
          
          %install
          rm -rf %{buildroot}
          mkdir -p %{buildroot}/%{_bindir}
          cp %{name} %{buildroot}/%{_bindir}
          
          %clean
          rm -rf %{buildroot}
          
          %files
          %{_bindir}/%{name}
          
          %changelog
          * Thu Mar 19 2024 Hakan İSMAİL <hakanismail53@gmail.com> - 2.0
          - Initial release
          EOF
          
      - name: Create binary folder
        run: mkdir vcandy-2.0

      - name: Move binary to binary folder
        run: mv /home/runner/work/Virtual-CANDY/Virtual-CANDY/dist/vcandy vcandy-2.0

      - name: Create .tar.gz file
        run: tar --create --file vcandy-2.0.tar.gz vcandy-2.0

      - name: Build RPM package
        run: rpmbuild -bb vcandy.spec

      - name: Upload RPM package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vcandy
          path: ~/rpmbuild/RPMS/**/*.rpm
